spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username:
    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  #set this so that sprinboot runs your scripts on startup
#  sql:
#    init:
#      mode: always

server:
  error:
    include-binding-errors: always #include message even if bean instantiation fails
    include-message: always #include error message in response body