CREATE SCHEMA testDb;

SET SCHEMA testDb;

CREATE TABLE users(
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    passowrd VARCHAR(100) NOT NULL
);

